esphome:
    name: open-ato-esp

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Open-Ato-Esp Fallback Hotspot"
    password: "yS0TVuS1ee4S"

captive_portal:

switch:
  - platform: gpio
    pin: D4
    name: "ATO Pump"
    id: ato_pump

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
    name: "Low level sensor"
    filters:
      - delayed_on: 5s
    on_press:
      then:
        - switch.toggle: ato_pump

#OLED Display
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

i2c:
  sda: D3
  scl: D5

font:
  - file: "fonts/ComicSansMS3.ttf"
    id: comic_sans_font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 0, id(comic_sans_font), TextAlign::TOP_CENTER, "ATO");
      
      // Print time in HH:MM format
      it.strftime(0, 60, id(comic_sans_font), TextAlign::BASELINE_LEFT, "%Y-%m-%d %H:%M:%S", id(sntp_time).now());      
      it.printf(127, 23, id(comic_sans_font), TextAlign::BASELINE_RIGHT , "%.1f°", id(ato_pump).state);          
